name: Deploy app to production

permissions:
  contents: write
  pull-requests: write


on:
  repository_dispatch:
    types: [limits-common-change]

jobs:
  cargo-update-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rust Setup
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "nightly-2025-01-09"
          targets: "wasm32-unknown-unknown"
          components: "clippy,rustfmt"

      - name: Update cargo dependencies
        run: cargo update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.LEPTOS_SSR_DISPATCH_TOKEN }}
          title: 'Cargo update: yral common updated ${{ github.event.client_payload.commit_hash }}'
          body: |
            Cargo update triggered by push to update to limits create in yral-common repository
            - Link to commit: (${{ github.event.client_payload.commit_hash }})[https://github.com/dolr-ai/yral-common/commit/${{ github.event.client_payload.commit_hash }}]
          commit-message: "Cargo update: limits changed ${{ github.event.client_payload.commit_hash }}"
          committer: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: cargo-update-yral-common-${{ github.event.client_payload.commit_hash }}
          add-paths: |
            Cargo.toml
          draft: false
          team-reviewers: |
            rust-full-stack
            